public enum Token { 
nord, 		// case 0
sud, 		// case 1
est, 		// case 2
ouest, 		// case 3
fois, 		// case 4
lever, 		// case 5
baisser,  	// case 6
origine,  	// case 7
pas,  		// case 8
point,  	// case 9
entier,  	// case 10
identificateur, // case 11
repeter,  	// case 12
fin,  		// case 13
definir,  	// case 14
eof,  		// case 15
erreur 		// case 16
}
